# Settings example to retrieve aerosol and surface parameters from synthetic POLDER (I, Q and U) observations (multi-pixel)
# Authors: Pavel Litvinov, Xin Huang, Anton Lopatin
# date of last modification: 2016-09-11 (Anton Lopatin)

# Other comments:
#   fast settings
#   monomodal triangular bins
#   monomodal spectral dependent refractive index
#   exponential aerosol vertical profile with retrieved scale altitude
#   both land and ocean surface
#   characteristics, optics, refractive index, surface, residual and size distribution bimodal properties provided

# This setting file has been updated to do retrievals from 1D/3D RT calculations for LES. 
# Last updated by Nirandi Jayasinghe, on 13th Aug 2024


input:
    driver: sdata
    file: example_LES.sdat


output:
    segment:
        function: classic
        stream: example_LES_inversion_test.txt #screen
        
retrieval:
    general:
        path_to_internal_files: /data/home/njayasinghe/grasp/src/retrieval/internal_files

    mode: inversion # forward
    
    inversion: 
        regime: single_pixel #multi_pixel   
        
        convergence:
            minimization_convention: logarithm
            threshold_for_stopping: 1.0e-6 # changed to e-3 to e-6
            maximum_iterations_for_stopping: 30 # changed from 15 to 30
            maximum_iterations_of_Levenberg-Marquardt: 30 # changed from 15 to 30
            threshold_for_stopping_Q_iterations:  1.0e-12
            scale_for_finite_difference:          5.0e-4 #chnaged from HARP
            normal_system_solver:       sparse_matrix_solver
            shift_for_applying_logarithm_to_negative_values: 1.1

        measurement_fitting:
            polarization: relative_polarization_components

        noises:
            noise[1]:
                standard_deviation_synthetic: 0.0
                error_type:   relative
                standard_deviation:  0.03
                measurement_type[1]:
                    type: I
                    index_of_wavelength_involved: [ 1 ]
            noise[2]:
                standard_deviation_synthetic: 0.0
                error_type:  absolute
                standard_deviation:  0.005
                measurement_type[1]:
                    type: Q
                    index_of_wavelength_involved: [ 1 ]
                measurement_type[2]:
                    type: U
                    index_of_wavelength_involved: [ 1 ]
                measurement_type[3]:
                    type: p_rel
                    index_of_wavelength_involved: [ 1 ]

    forward_model:
        phase_matrix:
            size_binning_method_for_triangle_bins: logarithm
            number_of_elements: 6 # different elements of phase matrix
            kernels_folder: "KERNELS_BASE/"
            radius:
                mode[1]:
                    min: 0.01
                    max: 15.0
                
                mode[2]:
                    min: 0.01
                    max: 15.0
                    
        radiative_transfer:
            number_of_layers: 50
            aerosol_profile_vertical_type:    exponential
            absolute_error_rt_calculations: 0.0005
            reference_plane_for_polarization:   meridian
            simulating_observation:
                order_of_scattering: multiple_scattering
                number_of_gaussian_quadratures_for_expansion_coefficients:  15
                number_of_guassian_quadratures_for_fourier_expansion_coefficients:  5
                number_of_fourier_expansion_coefficients:  4
            simulating_derivatives:
                order_of_scattering: multiple_scattering
                number_of_gaussian_quadratures_for_expansion_coefficients:  15
                number_of_guassian_quadratures_for_fourier_expansion_coefficients:   4
                number_of_fourier_expansion_coefficients:   4


    products: 
        #configuration:
            #wavelength_indices_for_angstrom: [1] #
            #wavelength_indices_for_ndvi: [1]
        aerosol:
            chemistry: false
            lidar: false                            
            optical_properties: true                
            phase_matrix: false                      
            refractive_index: true                 
            theoretical_bimodal_extinction: true    # should we change these to mono-modal ? no problem
            theoretical_bimodal_parameters: true  
            particulate_matter: false
            type: false
        error_estimation:
            aerosol:
                lidar: false            
                optical_properties: false
            parameters: false            
        forcing:
            broadband_flux: false                    
            forcing: false                           
        retrieval:
            fitting: true #changed to true                       
            parameters: true #changed to true                      
            residual: true #changed to true                        
        surface:
            main_characteristics: true 
            isotropic_bihemispherical_reflectance: false

    debug:
        additional_information: false
        verbose: true

    constraints:
        characteristic[1]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [1.0] # τfactor should not exceed unity #Cv
                    min: [0.00000001]
                    value: [0.001]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max: [5.0] #Cv
                    min: [0.00000001]
                    value: [0.002]
            retrieved: true
            type: aerosol_concentration
        characteristic[2]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [0.34, 0.60]# [rv, sigma] for size dst
                    min: [0.13, 0.35]
                    value: [0.17, 0.4]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0, 0]
                    max: [6.0, 0.77]# [rv, sigma] for size dst
                    min: [0.65, 0.3]
                    value: [1.0, 0.45]
            retrieved: true
            type: size_distribution_lognormal
        characteristic[3]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.6]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [1.6]
                    min: [1.33]
                    value: [1.4]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            retrieved: true
            type: real_part_of_refractive_index_spectral_dependent
        characteristic[4]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1] 
                    max: [0.01]
                    min: [1e-6]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max: [0.01]
                    min: [1e-6]
                    value: [0.002]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 2
                        lagrange_multiplier: 0.1
            retrieved: true
            type: imaginary_part_of_refractive_index_spectral_dependent
        characteristic[5]:
            type: surface_water_cox_munk_iso
            retrieved: true
            mode[1]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.000000002]
                    min:                            [0.000000001]
                    max:                            [0.000000003]
                    index_of_wavelength_involved:   [1]
                single_pixel:
                    smoothness_constraints:
                        difference_order: 1
                        lagrange_multiplier: 0.0
            mode[2]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.999999]
                    min:                            [0.999998]
                    max:                            [1.000000]
                    index_of_wavelength_involved:   [0]
            mode[3]:
                initial_guess:                       #1      #2      #3
                    value:                          [0.015]
                    min:                            [0.00406] # 1 m/s
                    max:                            [0.040] # 0.027 -> 10 m/s
                    index_of_wavelength_involved:   [0]
        characteristic[6]:
            type: vertical_profile_parameter_height
            retrieved: true
            mode[1]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0]
                    max:                            [20000.0]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1
                    value:                          [1000.0 ]
                    min:                            [500.0] 
                    max:                            [20000.0]
                    index_of_wavelength_involved:   [0      ]
#        DESERT INSPIRED (lower mins)
        characteristic[7]:
            mode[1]:
                initial_guess:                         #0.091086, 0.12525, 0.20794, 0.25698, 0.4415, 0.49488, 0.53105 , 0.6791  , 0.62972[DESERT]
                    index_of_wavelength_involved: [1] # 0.41 ,    0.443,   0.49 ,   0.555,   0.67 ,  0.865,   1.02 ,    1.65 ,    2.13 μm
                    max:                               [0.2,      0.2,     0.3,     0.4,     0.6,    0.7,     0.8,      1.0,      0.9]
                    min:                               [0.0050,   0.0050,  0.0050,  0.0050,  0.0050, 0.0200,  0.0200,   0.0200,   0.0200]
                    value:                             [0.1000,   0.1000,  0.2000,  0.3000,  0.4000, 0.5000,  0.5000,   0.7000,   0.6000]
                single_pixel:
                    smoothness_constraints: {difference_order: 2, lagrange_multiplier: 0}
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [1.0 ]
                    min:   [0.001]
                    value: [0.5 ]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            mode[3]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.5]
                    min:   [0.00001]
                    value: [0.05]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 0}
            retrieved: true
            type: surface_land_brdf_ross_li
        characteristic[8]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.9990000]
                    value: [0.9999998]
            mode[2]:
                initial_guess:
                    index_of_wavelength_involved: [0]
                    max:   [0.9999999]
                    min:   [0.0000001]
                    value: [0.9999998]
            retrieved: true
            type: sphere_fraction
        characteristic[9]:
            mode[1]:
                initial_guess:
                    index_of_wavelength_involved: [1]
                    max:   [10.0]
                    min:   [1.0]
                    value: [5.0]
                single_pixel:
                    smoothness_constraints: {difference_order: 1, lagrange_multiplier: 10}
            retrieved: true
            type: surface_land_polarized_maignan_breon
        characteristic[10]:
            type: vertical_profile_parameter_standard_deviation
            retrieved: false
            mode[1]:
                initial_guess:                      #1          
                    value:                          [1500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]
            mode[2]:
                initial_guess:                      #1          
                    value:                          [1500.0 ]
                    min:                            [200.0  ] 
                    max:                            [3000.0 ]
                    index_of_wavelength_involved:   [0      ]